# Generated by Django 3.1 on 2020-11-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinfo',
            name='app_type',
            field=models.IntegerField(choices=[(0, 'Node-微服务'), (1, 'Java-微服务'), (2, 'Java-API服务')], verbose_name='服务类型'),
        ),
    ]
