# Generated by Django 3.1 on 2020-11-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0002_auto_20201118_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='app_function',
            field=models.CharField(default='其他', max_length=32, verbose_name='所属业务'),
        ),
    ]
