# Generated by Django 3.1 on 2020-11-24 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0004_appinfo_deploy_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersionRecord',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False, verbose_name='服务版本id')),
                ('publish_id', models.IntegerField(verbose_name='服务上线id')),
                ('deploy_ids', models.CharField(max_length=32, verbose_name='提测记录ID列表')),
                ('app_name', models.CharField(max_length=64, verbose_name='服务名')),
                ('feature_branch', models.CharField(max_length=128, verbose_name='提测分支名')),
                ('test_branch', models.CharField(max_length=128, verbose_name='测试分支名')),
                ('test_branch_uuid', models.CharField(max_length=128, verbose_name='当前提测分支commit uuid')),
                ('release_branch', models.CharField(max_length=64, verbose_name='生成release分支名')),
                ('release_branch_uuid', models.CharField(max_length=64, verbose_name='生成release分支名')),
                ('publish_tag', models.CharField(max_length=64, verbose_name='生成tag名字')),
                ('maven_jar_version', models.CharField(max_length=64, verbose_name='依赖包maven仓库版本号')),
            ],
            options={
                'verbose_name': '服务部署版本记录表',
                'verbose_name_plural': '服务部署版本记录表',
                'db_table': 'vops_deploy_app_version',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeployAppEnv',
            fields=[
                ('env_id', models.AutoField(primary_key=True, serialize=False, verbose_name='环境id')),
                ('env_name', models.CharField(blank=True, max_length=32, verbose_name='环境名')),
                ('env_description', models.TextField(default='', verbose_name='环境描述')),
                ('env_kubeconf', models.TextField(default='', verbose_name='环境k8s配置文件')),
                ('env_namespace', models.CharField(blank=True, default='', max_length=24, verbose_name='环境k8s命名空间')),
            ],
            options={
                'verbose_name': '部署环境',
                'verbose_name_plural': '部署环境',
                'db_table': 'vops_deploy_app_env',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeployAppPublishRecord',
            fields=[
                ('publish_id', models.AutoField(primary_key=True, serialize=False, verbose_name='服务上线记录id')),
                ('description', models.TextField(default='', verbose_name='上线描述')),
                ('deploy_ids', models.CharField(max_length=32, verbose_name='提测记录ID列表')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('publish_env', models.ManyToManyField(blank=True, to='deploymanage.DeployAppEnv', verbose_name='上线环境')),
            ],
            options={
                'verbose_name': '服务上线记录表',
                'verbose_name_plural': '服务上线记录表',
                'db_table': 'vops_publish_record',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeployAppRecord',
            fields=[
                ('deploy_id', models.AutoField(primary_key=True, serialize=False, verbose_name='服务发布记录id')),
                ('app_name', models.CharField(max_length=100, verbose_name='服务名')),
                ('feature_branch', models.CharField(max_length=128, verbose_name='提测特性分支名')),
                ('feature_branch_uuid', models.CharField(max_length=500, verbose_name='提测特性分支UUID')),
                ('auto_test_branch', models.CharField(max_length=128, verbose_name='提测生成测试分支')),
                ('auto_test_branch_uuid', models.CharField(max_length=500, verbose_name='提测生成测试分支UUID')),
                ('deploy_status', models.CharField(choices=[('Pending', '待编译'), ('Compiling', '编译中'), ('CompileFailed', '编译失败'), ('DeployFailed', '部署失败'), ('DeployPass', '部署成功')], max_length=32, verbose_name='发布状态')),
                ('test_status', models.CharField(choices=[('WaitTest', '待测试'), ('TestNotPass', '未通过测试'), ('TestPass', '测试通过')], max_length=32, verbose_name='测试状态')),
                ('publish_status', models.IntegerField(choices=[(0, '未上线'), (1, '已上线')], default=0, verbose_name='上线状态')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='上线时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建人')),
                ('test_user', models.CharField(max_length=32, verbose_name='测试人')),
                ('deploy_env', models.ManyToManyField(blank=True, to='deploymanage.DeployAppEnv', verbose_name='发布环境')),
            ],
            options={
                'verbose_name': '服务提测记录表',
                'verbose_name_plural': '服务提测记录表',
                'db_table': 'vops_deploy_app_record',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeployAppRecordDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False, verbose_name='服务发布详情id')),
                ('compile_log', models.TextField(default='', verbose_name='编译日志')),
                ('deploy_log', models.TextField(default='', verbose_name='部署日志')),
                ('update_log', models.TextField(default='', verbose_name='操作日志')),
                ('test_image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='提测镜像地址')),
                ('deploy_app_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deploymanage.deployapprecord')),
            ],
            options={
                'verbose_name': '服务提测记录详情表',
                'verbose_name_plural': '服务提测记录详情表',
                'db_table': 'vops_deploy_app_record_detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeployAppPublishRecordDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False, verbose_name='服务上线详情id')),
                ('compile_log', models.TextField(default='', verbose_name='编译日志')),
                ('deploy_log', models.TextField(default='', verbose_name='部署日志')),
                ('update_log', models.TextField(default='', verbose_name='操作日志')),
                ('release_image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='上线镜像地址')),
                ('deploy_app_publish_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deploymanage.deployapppublishrecord')),
            ],
            options={
                'verbose_name': '服务上线详情表',
                'verbose_name_plural': '服务上线详情表',
                'db_table': 'vops_publish_record_detail',
                'managed': True,
            },
        ),
    ]
