# Generated by Django 3.1 on 2020-11-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0006_auto_20201124_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployapprecord',
            name='description',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='功能描述'),
        ),
    ]
