# Generated by Django 3.1 on 2020-11-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0009_auto_20201126_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployappenv',
            name='project_prefix',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='jenkins工程前缀'),
        ),
        migrations.AddField(
            model_name='deployappenv',
            name='project_sufix',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='jenkins工程后缀'),
        ),
    ]
