# Generated by Django 3.1 on 2020-11-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0010_auto_20201126_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployapprecord',
            name='jenkins_log_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='jenkins日志url'),
        ),
    ]
