# Generated by Django 3.1 on 2020-11-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0011_deployapprecord_jenkins_log_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployappenv',
            name='jenkins_folder_depth',
            field=models.IntegerField(blank=True, default=0, verbose_name='jenkins工程目录深度'),
        ),
    ]
