# Generated by Django 3.1 on 2020-11-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0012_deployappenv_jenkins_folder_depth'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersionHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False, verbose_name='版本历史表id')),
                ('app_name', models.CharField(max_length=500, verbose_name='服务名')),
                ('release_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='版本名')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '服务版本历史记录表',
                'verbose_name_plural': '服务版本历史记录表',
                'db_table': 'vops_deploy_app_version_history',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='appversionrecord',
            name='deploy_ids',
        ),
        migrations.AddField(
            model_name='appversionrecord',
            name='child_app_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='子工程服务名'),
        ),
        migrations.AddField(
            model_name='appversionrecord',
            name='create_time',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='appversionrecord',
            name='parent_app_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='父工程服务名'),
        ),
        migrations.AddField(
            model_name='deployapppublishrecord',
            name='dependence_str',
            field=models.TextField(null=True, verbose_name='依赖包及分支列表 以,分隔'),
        ),
        migrations.AlterField(
            model_name='appversionrecord',
            name='release_branch_uuid',
            field=models.CharField(max_length=64, verbose_name='生成release分支uuid'),
        ),
    ]
