# Generated by Django 3.1 on 2020-11-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0013_auto_20201127_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversionhistory',
            name='service_relation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='服务对应关系'),
        ),
        migrations.AddField(
            model_name='appversionrecord',
            name='service_relation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='服务对应关系'),
        ),
    ]
