# Generated by Django 3.1 on 2020-11-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0015_auto_20201130_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployapppublishrecord',
            name='app_name',
            field=models.CharField(max_length=200, null=True, verbose_name='服务名'),
        ),
    ]
