# Generated by Django 3.1 on 2020-11-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0016_deployapppublishrecord_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployapppublishrecord',
            name='jenkins_log_url',
            field=models.CharField(max_length=500, null=True, verbose_name='jenkins日志链接'),
        ),
    ]
