# Generated by Django 3.1 on 2020-12-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0017_deployapppublishrecord_jenkins_log_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployapppublishrecord',
            name='publish_user',
            field=models.CharField(max_length=32, null=True, verbose_name='验证人'),
        ),
    ]
