# Generated by Django 3.1 on 2020-12-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0019_auto_20201203_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversionhistory',
            name='release_uuid',
            field=models.CharField(max_length=64, null=True, verbose_name='生成release分支uuid'),
        ),
    ]
