# Generated by Django 3.1 on 2020-12-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0020_appversionhistory_release_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployapppublishrecord',
            name='release_status',
            field=models.IntegerField(null=True, verbose_name='版本生成状态'),
        ),
    ]
