# Generated by Django 3.1 on 2020-12-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0023_deployapprecord_is_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployapppublishrecord',
            name='release_status',
            field=models.IntegerField(choices=[(0, '待生成'), (1, '已生成'), (2, '生成失败')], default=0, verbose_name='版本生成状态'),
        ),
    ]
