# Generated by Django 3.1 on 2020-12-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0024_auto_20201207_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployapprecord',
            name='is_deleted',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否已删除'),
        ),
    ]
