# Generated by Django 3.1 on 2020-12-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0025_deployapprecord_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBranchStatus',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False, verbose_name='分支id')),
                ('app_name', models.CharField(max_length=100, verbose_name='服务名')),
                ('branch_name', models.CharField(max_length=500, verbose_name='分支名字')),
                ('is_deleted', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否已删除')),
                ('is_merged', models.IntegerField(choices=[(0, '未合并'), (1, '已合并')], default=0, verbose_name='合并状态')),
                ('branch_type', models.IntegerField(choices=[(0, '功能分支'), (1, '测试分支'), (2, '发布分支')], default=0, verbose_name='分支类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_by', models.CharField(max_length=32, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '分支状态表',
                'verbose_name_plural': '分支状态表',
                'db_table': 'vops_deploy_branch_status',
                'managed': True,
            },
        ),
    ]
