# Generated by Django 3.1 on 2020-12-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0026_appbranchstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployapppublishrecord',
            name='branch_status',
            field=models.IntegerField(choices=[(0, '未合并'), (1, '已合并')], default=0, verbose_name='分支状态'),
        ),
    ]
