# Generated by Django 3.1 on 2020-12-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0027_deployapppublishrecord_branch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversionrecord',
            name='is_conflicted',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='合并是否有冲突'),
        ),
    ]
