# Generated by Django 3.1 on 2021-01-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0029_auto_20210105_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployapppublishrecord',
            name='merge_status',
            field=models.IntegerField(choices=[(0, '无冲突'), (1, '有冲突')], default=0, verbose_name='合并状态'),
        ),
    ]
