# Generated by Django 3.1 on 2021-01-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploymanage', '0030_deployapppublishrecord_merge_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmHostInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='虚拟机id')),
                ('hostname', models.CharField(max_length=200, verbose_name='虚拟机名')),
                ('ip', models.CharField(max_length=32, verbose_name='虚拟机IP')),
                ('physical_hostname', models.CharField(max_length=200, verbose_name='宿主机名')),
                ('is_deleted', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
                ('group', models.CharField(max_length=200, null=True, verbose_name='主机所属业务组')),
                ('area', models.CharField(max_length=200, null=True, verbose_name='主机所属区域')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '虚拟机列表',
                'verbose_name_plural': '虚拟机列表',
                'db_table': 'vm_hosts',
                'managed': True,
            },
        ),
    ]
