# Generated by Django 3.1 on 2020-11-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0002_auto_20201106_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('menu_dashboard', '菜单 Dashboard'), ('menu_system_configure', '菜单 系统配置'), ('menu_deploymanage', '菜单 发布管理'), ('menu_deploymanage_appdeploy', '菜单 项目上线'))},
        ),
        migrations.AlterField(
            model_name='users',
            name='display',
            field=models.CharField(default='', max_length=50, verbose_name='姓名'),
        ),
    ]
