# Generated by Django 3.1 on 2020-11-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0004_auto_20201118_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('menu_dashboard', '菜单 Dashboard'), ('menu_system_configure', '菜单 系统配置'), ('menu_deploymanage', '菜单 发布管理'), ('menu_deploymanage_servicemanage', '菜单 微服务管理'), ('menu_deploymanage_addservice', '菜单 服务配置'), ('menu_deploymanage_getservice', '菜单 服务获取'))},
        ),
    ]
