# Generated by Django 3.1 on 2020-11-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0014_users_tel_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('menu_dashboard', '菜单 Dashboard'), ('menu_system_configure', '菜单 系统配置'), ('menu_deploymanage', '菜单 发布管理'), ('menu_deploymanage_servicemanage', '菜单 服务定义 服务列表'), ('menu_deploymanage_bindservice', '菜单 服务定义 服务绑定'), ('menu_deploymanage_addservice', '菜单 服务定义 服务添加'), ('menu_deploymanage_delservice', '菜单 服务定义 服务删除'), ('menu_deploymanage_resetservice', '菜单 服务定义 依赖重置'), ('menu_deploymanage_getservice', '菜单 服务定义 服务获取'), ('menu_deploymanage_updateservice', '菜单 服务定义 服务修改'), ('menu_deploymanage_versiontest', '菜单 版本提测 版本列表'), ('menu_deploymanage_addversion', '菜单 版本提测 添加版本'), ('menu_deploymanage_getversion', '菜单 版本提测 获取版本'), ('menu_deploymanage_updateversion', '菜单 版本提测 修改版本'), ('menu_deploymanage_passversion', '菜单 版本提测 版本测试操作'), ('menu_deploymanage_deployversion', '菜单 版本提测 发布版本'), ('menu_deploymanage_versionpublish', '菜单 版本上线 版本列表'), ('menu_deploymanage_addpublish', '菜单 版本上线 添加上线版本'), ('menu_deploymanage_getpublish', '菜单 版本上线 获取上线版本'), ('menu_deploymanage_updatepublish', '菜单 版本上线 更新上线版本'))},
        ),
    ]
